name: BILIBILI_HELPER

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '10 1 * * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时


jobs:
  start:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Jar
        run: chmod +x download.sh && bash download.sh
      - name: Run
        env:
          BILI_JCT: ${{ secrets.BILI_JCT }}
          DEDEUSERID: ${{ secrets.DEDEUSERID }}
          SESSDATA: ${{ secrets.SESSDATA }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run:
          java -jar BILIBILI-HELPER.jar ${DEDEUSERID} ${SESSDATA} ${BILI_JCT} ${SERVERPUSHKEY}
